### ISSUE TITLE
Valid parquet v1 file test/test-files.parquet fails to be read by tests in integration.js

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/parquetjs#103] opened 2023-11-21 19:11 UTC
### Steps to reproduce
There are other ways to test this but this is the easiest:

1. Verify that  all the tests in test/integration.js pass:
    ```shell
    mocha -r ts-node/register test/integration.js
    ```
2. Change function `sampleColumnHeaders` in `test/integration.ts` to point at `test/test-files/fruits.parquet` and not `fruits.parquet` (which actually is a generated file created by other tests in this file).
3. Run one of the integration tests, for example:
    ```shell
    mocha -r ts-node/register -f "verify statistics" test/integration.js
    ```
4. Note that two tests fail in util.ts in with 'read failed'.  

### Expected behaviour
I would expect the statistics tests to fail, but only due to the statistics values, not in the buffer read.  If you import test/test-files/fruits.parquet into https://parquetreader.com, the file is parsed just fine.  That leads me to believe it's a bug in this repo.

### Actual behaviour
When debugging this failure, I found the error originates from readFooter.  It appears to read bytes beyond the length of the buffer.  When I stepped into the code I found the error being thrown in util.ts, function fread, line 133. The file fruits.parquet read failed here because length = 8 and bytesRead = 4.  The position was -4.  So it appears the read was trying to go 4 bytes past the end of the buffer.

### Any logs, error output, etc?
```shell
 1) Parquet
       with DataPageHeaderV1
         verify statistics:
     Error: read failed
      at ~/github/parquetjs/lib/util.ts:133:23
      at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)
```

### Any other comments?
I haven't done more debugging to find out why this is failing, and have not checked the commits to see when the bug appeared.

**Comment by andresgutgon** [comment] 2024-05-17 16:40
Hi @shannonwells any luck with this?

**Comment by andresgutgon** [comment] 2024-05-21 07:57
☝️ In my case was a stupid mistake

I forgot to `await writer.close()` 🙈

**Comment by JoeCap08055** [comment] 2024-07-03 17:43
Followed steps to reproduce, was unable to reproduce. Consulted with @shannonwells who concurred to simply close this.

**Closed by JoeCap08055** 2024-07-03 17:43 UTC
Labels: bug
