### ISSUE TITLE
Error processing parquet file: invalid compression method: ZSTD

### ISSUE THREAD

**Issue by vedantroy** [LibertyDSNP/parquetjs#150] opened 2024-10-28 19:47 UTC
Thanks for reporting an issue!

### Steps to reproduce

When I try to open a valid parquet file (pandas can open it):
```
        console.log('opening')
		const reader = await parquet.ParquetReader.openFile(values["input-file"]);
        console.log('reading')
		const cursor = reader.getCursor();
        console.log('cursor')
		
		let record = null;
		let count = 0;
        console.log('looping')
		while ((record = await cursor.next())) {
			console.log(record);
			count++;
		}
```

I get the error:
```
Error processing parquet file: invalid compression method: ZSTD
```

Package version: `1.8.5`

I will try to give a sample parquet file to aid in debugging.

**Comment by wilwade** [comment] 2024-10-29 12:42
@vedantroy Currently we do not have support for zstd compression. Open to PRs for it.

Duplicate of https://github.com/LibertyDSNP/parquetjs/issues/77

**Closed by wilwade** 2024-10-29 12:42 UTC
